use headless service

diff --git a/argocd/charts/iperf3/templates/deployment.yaml b/argocd/charts/iperf3/templates/deployment.yaml
--- a/argocd/charts/iperf3/templates/deployment.yaml
+++ b/argocd/charts/iperf3/templates/deployment.yaml
@@ -69,6 +69,9 @@ spec:
               {{- if .Values.client.runForever }}
               while true; do
               {{- end }}
+                echo "Resolving target host {{ .Values.client.targetHost }}..."
+                nslookup {{ .Values.client.targetHost }} || echo "nslookup failed, continuing anyway"
+                echo "Starting iperf3 test..."
                 {{ include "iperf3.clientCommand" . }}
               {{- if .Values.client.runForever }}
                 {{- if gt (int .Values.client.waitSeconds) 0 }}
